### ISSUE TITLE
Upgrade h3 version in Java monorepo

### ISSUE THREAD

**Issue by ameeta-uber** [uber/h3-java#116]
Java mono repo is on v3.6.3 for h3. This is causing build failures on M1 laptops due to the following exception. The suggested fix for this is to upgrade h3 version to 3.7.x or greater. We need a new point release with support for M1 + older glibc (2.26)

`java.lang.UnsatisfiedLinkError: No native resource found at /darwin-arm64/libh3-java.dylib
	at com.uber.h3core.H3CoreLoader.copyResource(H3CoreLoader.java:68)
	at com.uber.h3core.H3CoreLoader.loadNatives(H3CoreLoader.java:120)
	at com.uber.h3core.H3CoreLoader.loadNatives(H3CoreLoader.java:89)
	at com.uber.h3core.H3Core.newInstance(H3Core.java:79)
	at com.uber.sia.common.geo.H3GeoAnalyzer.<init>(H3GeoAnalyzer.java:34)
	at com.uber.sia.common.geo.GeoHelper.<init>(GeoHelper.java:76)
	at com.uber.marketplace.fulfillment.indexing.gateway.core.sia.ingestion.LocationMapper.analyzeLocation(LocationMapper.java:112)`

`grep h3 /home/user/fievel/3rdparty/jvm/com/uber/BUCK
    name = "h3-3.6.3.jar",
    maven_coords = "com.uber:h3:jar:3.6.3",`

I am unable to use my local environment for development and have to use devpod which is quite slow and is affecting productivity.

**Comment by ajfriend** [comment]
I think the ask here is for a new 3.7 release supporting older glibc on M1 macs.

**Comment by isaacbrodsky** [comment]
Hi @ameeta-uber, h3-java version `3.7.3` is now released with backported GLIBC 2.26 support and Apple M1. Please let me know if this works for you.

Obviously upgrading to 4.x.x may be difficult in your case, I suggest working with @ajfriend on if that's possible.

**Comment by safavi** [comment]
@isaacbrodsky - Thanks Isaac. Seems to be working.
